# Generated by Django 6.0.3 on 2026-07-27 01:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lojas', '0001_initial'),
        ('produtos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusPedido',
            fields=[
                ('status_pedido_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=55, unique=True)),
            ],
            options={
                'verbose_name': 'status do pedido',
                'verbose_name_plural': 'status dos pedidos',
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('pedido_id', models.AutoField(primary_key=True, serialize=False)),
                ('valor_bruto', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('valor_desconto', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('valor_liquido', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('loja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to='lojas.loja')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to=settings.AUTH_USER_MODEL)),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos', to='pedidos.statuspedido')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PedidoCliente',
            fields=[
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('pedido_cliente_id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=150)),
                ('cpf', models.CharField(max_length=11)),
                ('email', models.EmailField(max_length=254)),
                ('data_nascimento', models.DateField()),
                ('genero', models.CharField(max_length=55)),
                ('pedido', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cliente', to='pedidos.pedido')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PedidoProduto',
            fields=[
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('pedido_produto_id', models.AutoField(primary_key=True, serialize=False)),
                ('nome_produto', models.CharField(max_length=155)),
                ('quantidade', models.PositiveIntegerField()),
                ('valor_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor_desconto', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='pedidos.pedido')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produtos.produto')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
