# Generated by Django 6.0.3 on 2026-08-04 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidocliente',
            name='telefone',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
