# Generated by Django 6.0.3 on 2026-08-04 23:36

from django.db import migrations, models


def criar_generos_padrao(apps, schema_editor):
    Genero = apps.get_model('usuarios', 'Genero')
    for codigo, descricao in [('M', 'Masculino'), ('F', 'Feminino'), ('I', 'Indefinido')]:
        Genero.objects.get_or_create(genero=descricao, defaults={'id_genero': codigo})


def remover_generos_padrao(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='solicitacao_produtor_pendente',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usuario',
            name='telefone',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.RunPython(criar_generos_padrao, remover_generos_padrao),
    ]
