# Generated by Django 6.0.3 on 2026-08-05 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_usuario_solicitacao_produtor_pendente_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='solicitacao_produtor_pendente',
        ),
    ]
